name: 'brew tap install and test'
description: 'setup homebrew and test formula.'
author: 'curoky'
branding:
  icon: 'box'
  color: 'gray-dark'
inputs:
  formula:
    description: formula
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: install deps
      shell: bash
      run: brew install jq

    - name: setup user tap
      shell: bash
      run: |
        mkdir -p $(brew --repo)/Library/Taps/curoky
        cp -r $PWD $(brew --repo)/Library/Taps/curoky/homebrew-custom

    - name: show tap formula
      shell: bash
      run: brew tap-info curoky/custom --json | jq -r '.[]|(.formula_names[],.cask_tokens[])'

    - name: install formula
      shell: bash
      run: brew install --verbose ${{ inputs.formula }}

    - name: test formula
      shell: bash
      run: brew test ${{ inputs.formula }} || brew reinstall ${{ inputs.formula }}

    - name: test formula twice
      shell: bash
      run: brew test ${{ inputs.formula }}
