name: commit file filter

on:
  push:
    paths:
      - .github/workflows/commit-file-filter.yaml

jobs:
  commit_file_filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: >
          git diff-tree --no-commit-id --name-only -r
          ${{ github.event.before }}
          ${{ github.event.after }} > list.txt

      - id: xxx
        run: |
          if grep -q "xxx" ./list.txt; then
            echo "::set-output name=used::true"
          else
            echo "::set-output name=used::false"
          fi
