name: login runner with tmux

on:
  push:
    paths:
      - .github/workflows/login-runner-tmux.yaml

jobs:
  connect:
    strategy:
      matrix:
        # ubuntu-20.04 # 16/18/20 or macos-10.15 or windows-2019
        os: [macos-latest, ubuntu-20.04]

    runs-on: ${{ matrix.os }}
    steps:
      # For continue, run `sudo touch /continue`
      - name: Setup tmate session
        if: ${{ always() }}
        uses: mxschmitt/action-tmate@v3

      # only support ubuntu
      - uses: curoky/actions/tmate@master
        if: ${{ failure() }}
